GET http://localhost:3000/user/list

###

POST http://localhost:3000/user/add
Content-Type: application/json

{
    "name": "Domenico Valentino",
    "email": "domenico2727@gmail.com",
    "password": "Passowrd5!"
}